version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - npm install -g aws-cdk
      - echo Installing aws-cdk-lib==2.173.2...
      - pip install aws-cdk-lib==2.173.2 
  build:
    commands:
      - node -v  # Check Node.js version
      - npm -v   # Check npm version
      - pip -V # Check pip version
      - python -V # Check  python version
      - echo Synthesizing CDK stack...
      - npx cdk synth --output cdk.out
      - cp cdk.out/*.template.json .  # Copy all template files to the root directory
      - echo Zipping Lambda function code...
      - zip -r lambda_function.zip knowlio/src 
      - echo Copying Lambda source files to output directory...
      - mkdir -p cdk.out/src  # Ensure src directory exists in cdk.out
      - cp -R knowlio/src/* cdk.out/src  # Copy Lambda source files to cdk.out/src
      - echo "Contents of current directory after copying:"
      - ls -la
      - echo "deploying all CDKs"
      - npx cdk deploy --all --force --region us-west-2
artifacts:
  files:
    - '*.template.json'
    - 'cdk.out/**/*'
    - 'lambda_function.zip'
  name: cdk-artifacts

cache:
  paths:
    - '/root/.npm/**/*'
    - '/root/.pip-cache/**/*'